# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

jobs:
- job: macOS

  pool:
    vmImage: 'macOS 10.13'

  steps:
  - script: |
      sw_vers
      /usr/libexec/PlistBuddy -c Print /Applications/Safari.app/Contents/Info.plist
    displayName: 'info'

  - script: ./install.sh
    displayName: 'Install Safari Technology Preview'

- job: Windows

  pool:
    vmImage: 'VS2017-Win2016'

  steps:
  - script: |
      dir
    displayName: 'Testa testa'
