# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

jobs:
- job: macOS
  displayName: 'macOS job with spaces'

  pool:
    vmImage: 'macOS 10.13'

  steps:
  - script: ./install.sh
    displayName: 'Install Safari Technology Preview'
