version: 2
jobs:
  build:
    macos:
      xcode: "12.0.0"

    steps:
      - checkout
      - run: ./install.sh
      - run: python screenshot.py
      - run: mkdir /tmp/artifacts
      - run: mv screenshot.png /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts
