on: push
name: safari
jobs:
  safari:
    runs-on: macOS-10.15
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install
      run:  ./install.sh
    - name: Screenshot
      run: python screenshot.py
